"""migrate_text_to_enums

Revision ID: 34df0215a921
Revises: 689e89d7b2ee
Create Date: 2026-04-01 05:43:07.902712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34df0215a921'
down_revision: Union[str, Sequence[str], None] = '689e89d7b2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finding_truth_status', sa.Enum('VALIDATED', 'OVERTURNED', 'TOO_AGGRESSIVE', 'MISSED_PREVIOUSLY', 'UNRESOLVED', name='truthstatusenum'), nullable=True))
        batch_op.add_column(sa.Column('recommendation_truth_status', sa.Enum('VALIDATED', 'OVERTURNED', 'TOO_AGGRESSIVE', 'MISSED_PREVIOUSLY', 'UNRESOLVED', name='truthstatusenum'), nullable=True))
        batch_op.drop_column('truth_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truth_status', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('recommendation_truth_status')
        batch_op.drop_column('finding_truth_status')

    # ### end Alembic commands ###
