"""add_learning_truth_and_comments

Revision ID: 689e89d7b2ee
Revises: c33224e3dfa4
Create Date: 2026-04-01 05:39:04.796276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689e89d7b2ee'
down_revision: Union[str, Sequence[str], None] = 'c33224e3dfa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finding_reviews', sa.Column('finding_reason_comment', sa.Text(), nullable=True))
    op.add_column('finding_reviews', sa.Column('recommendation_reason_comment', sa.Text(), nullable=True))
    op.add_column('finding_reviews', sa.Column('truth_status', sa.String(), nullable=True))
    op.add_column('finding_reviews', sa.Column('validation_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finding_reviews', 'validation_source')
    op.drop_column('finding_reviews', 'truth_status')
    op.drop_column('finding_reviews', 'recommendation_reason_comment')
    op.drop_column('finding_reviews', 'finding_reason_comment')
    # ### end Alembic commands ###
