"""refine_learning_candidate

Revision ID: 76d1e359f00e
Revises: d22f18163790
Create Date: 2026-04-01 05:59:01.254590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d1e359f00e'
down_revision: Union[str, Sequence[str], None] = 'd22f18163790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_fingerprint', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('implementation_status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('admin_note', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_learning_candidates_candidate_fingerprint'), ['candidate_fingerprint'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_candidates_candidate_fingerprint'))
        batch_op.drop_column('admin_note')
        batch_op.drop_column('implementation_status')
        batch_op.drop_column('candidate_fingerprint')

    # ### end Alembic commands ###
