"""add_partial_validation_enum

Revision ID: bc0630e3b358
Revises: 34df0215a921
Create Date: 2026-04-01 05:50:07.551104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0630e3b358'
down_revision: Union[str, Sequence[str], None] = '34df0215a921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_reviews', schema=None) as batch_op:
        batch_op.alter_column('finding_truth_status',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('VALIDATED', 'PARTIAL_VALIDATION', 'OVERTURNED', 'TOO_AGGRESSIVE', 'MISSED_PREVIOUSLY', 'UNRESOLVED', name='truthstatusenum'),
               existing_nullable=True)
        batch_op.alter_column('recommendation_truth_status',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.Enum('VALIDATED', 'PARTIAL_VALIDATION', 'OVERTURNED', 'TOO_AGGRESSIVE', 'MISSED_PREVIOUSLY', 'UNRESOLVED', name='truthstatusenum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding_reviews', schema=None) as batch_op:
        batch_op.alter_column('recommendation_truth_status',
               existing_type=sa.Enum('VALIDATED', 'PARTIAL_VALIDATION', 'OVERTURNED', 'TOO_AGGRESSIVE', 'MISSED_PREVIOUSLY', 'UNRESOLVED', name='truthstatusenum'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)
        batch_op.alter_column('finding_truth_status',
               existing_type=sa.Enum('VALIDATED', 'PARTIAL_VALIDATION', 'OVERTURNED', 'TOO_AGGRESSIVE', 'MISSED_PREVIOUSLY', 'UNRESOLVED', name='truthstatusenum'),
               type_=sa.VARCHAR(length=17),
               existing_nullable=True)

    # ### end Alembic commands ###
