"""baseline

Revision ID: c33224e3dfa4
Revises: 
Create Date: 2026-04-01 04:52:05.224398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33224e3dfa4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_records_asset_id'), 'asset_records', ['asset_id'], unique=True)
    op.create_index(op.f('ix_asset_records_audit_id'), 'asset_records', ['audit_id'], unique=False)
    op.create_table('asset_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('system_support_quality', sa.String(), nullable=True),
    sa.Column('auditor_verdict', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'finding_id', 'asset_id', name='uq_asset_verdict')
    )
    op.create_index(op.f('ix_asset_verdicts_asset_id'), 'asset_verdicts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_verdicts_audit_id'), 'asset_verdicts', ['audit_id'], unique=False)
    op.create_index(op.f('ix_asset_verdicts_finding_id'), 'asset_verdicts', ['finding_id'], unique=False)
    op.create_table('audit_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('claim_readiness', sa.String(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_runs_audit_id'), 'audit_runs', ['audit_id'], unique=True)
    op.create_table('carrier_guidelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('hermes_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_guidelines_carrier'), 'carrier_guidelines', ['carrier'], unique=False)
    op.create_table('claim_audit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_audit_records_audit_id'), 'claim_audit_records', ['audit_id'], unique=True)
    op.create_index(op.f('ix_claim_audit_records_claim_number'), 'claim_audit_records', ['claim_number'], unique=False)
    op.create_table('claim_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(), nullable=False),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('loss_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_records_claim_number'), 'claim_records', ['claim_number'], unique=True)
    op.create_table('finding_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.Column('health_explanation', sa.Text(), nullable=True),
    sa.Column('is_unresolved_override', sa.Boolean(), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('evidence_exists', sa.String(), nullable=True),
    sa.Column('evidence_uploaded', sa.String(), nullable=True),
    sa.Column('linked_asset_ids', sa.Text(), nullable=True),
    sa.Column('missing_upload_reason', sa.String(), nullable=True),
    sa.Column('hermes_critique', sa.Text(), nullable=True),
    sa.Column('auditor_outcome', sa.String(), nullable=True),
    sa.Column('auditor_reason_code', sa.String(), nullable=True),
    sa.Column('guideline_citation', sa.String(), nullable=True),
    sa.Column('suggested_action_type', sa.String(), nullable=True),
    sa.Column('suggested_revision', sa.JSON(), nullable=True),
    sa.Column('requires_manual_confirmation', sa.Boolean(), nullable=True),
    sa.Column('supporting_reason', sa.Text(), nullable=True),
    sa.Column('recommendation_outcome', sa.String(), nullable=True),
    sa.Column('recommendation_reason_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id', 'finding_id', name='uq_finding_review')
    )
    op.create_index(op.f('ix_finding_reviews_audit_id'), 'finding_reviews', ['audit_id'], unique=False)
    op.create_index(op.f('ix_finding_reviews_finding_id'), 'finding_reviews', ['finding_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('audit_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_audit_id'), 'processing_jobs', ['audit_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_job_id'), 'processing_jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_job_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_audit_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_finding_reviews_finding_id'), table_name='finding_reviews')
    op.drop_index(op.f('ix_finding_reviews_audit_id'), table_name='finding_reviews')
    op.drop_table('finding_reviews')
    op.drop_index(op.f('ix_claim_records_claim_number'), table_name='claim_records')
    op.drop_table('claim_records')
    op.drop_index(op.f('ix_claim_audit_records_claim_number'), table_name='claim_audit_records')
    op.drop_index(op.f('ix_claim_audit_records_audit_id'), table_name='claim_audit_records')
    op.drop_table('claim_audit_records')
    op.drop_index(op.f('ix_carrier_guidelines_carrier'), table_name='carrier_guidelines')
    op.drop_table('carrier_guidelines')
    op.drop_index(op.f('ix_audit_runs_audit_id'), table_name='audit_runs')
    op.drop_table('audit_runs')
    op.drop_index(op.f('ix_asset_verdicts_finding_id'), table_name='asset_verdicts')
    op.drop_index(op.f('ix_asset_verdicts_audit_id'), table_name='asset_verdicts')
    op.drop_index(op.f('ix_asset_verdicts_asset_id'), table_name='asset_verdicts')
    op.drop_table('asset_verdicts')
    op.drop_index(op.f('ix_asset_records_audit_id'), table_name='asset_records')
    op.drop_index(op.f('ix_asset_records_asset_id'), table_name='asset_records')
    op.drop_table('asset_records')
    # ### end Alembic commands ###
