"""phase_5_impact

Revision ID: cfe8651a88f7
Revises: e82f4df78593
Create Date: 2026-04-01 07:07:29.003408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe8651a88f7'
down_revision: Union[str, Sequence[str], None] = 'e82f4df78593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('effectiveness_status', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('impact_summary_json', sa.JSON(), nullable=True))
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('impact_summary_json')
        batch_op.drop_column('effectiveness_status')
        batch_op.drop_column('prompt_version')

    # ### end Alembic commands ###
