"""add_learning_candidates_table

Revision ID: d22f18163790
Revises: bc0630e3b358
Create Date: 2026-04-01 05:57:49.428458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22f18163790'
down_revision: Union[str, Sequence[str], None] = 'bc0630e3b358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('RULE_ADJUSTMENT', 'WORDING_ADJUSTMENT', 'RECOMMENDATION_TUNING', 'MISSED_PATTERN_ALERT', 'CARRIER_SPECIFIC_BEHAVIOR', name='learningcandidatetype'), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_candidates')
    # ### end Alembic commands ###
