"""candidate_impact_linkage

Revision ID: e82f4df78593
Revises: 76d1e359f00e
Create Date: 2026-04-01 07:00:36.457831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82f4df78593'
down_revision: Union[str, Sequence[str], None] = '76d1e359f00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('git_commit_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('change_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rule_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('deployed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('implemented_by', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_candidates', schema=None) as batch_op:
        batch_op.drop_column('verification_status')
        batch_op.drop_column('implemented_by')
        batch_op.drop_column('deployed_at')
        batch_op.drop_column('rule_version')
        batch_op.drop_column('change_type')
        batch_op.drop_column('git_commit_hash')

    # ### end Alembic commands ###
